Minor changes

diff --git a/templates/nginx.j2 b/templates/nginx.j2
--- a/templates/nginx.j2
+++ b/templates/nginx.j2
@@ -1,4 +1,5 @@
 #! /bin/sh
+
 ### BEGIN INIT INFO
 # Provides:          nginx
 # Required-Start:    $all
@@ -8,72 +9,64 @@
 # Short-Description: starts nginx
 # Description:       starts the NGINX Manager daemon
 ### END INIT INFO
- 
-. /lib/lsb/init-functions
 
+. /lib/lsb/init-functions
 #------------------------------------------------------------------------------
 #                               Consts
-#------------------------------------------------------------------------------
-
 #------------------------------------------------------------------------------
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/sbin/
 DAEMON=/usr/sbin/nginx
 PS="nginx"
-PIDNAME="nginx"				#lets you do $PS-slave
+PIDNAME="nginx"             #lets you do $PS-slave
 PIDFILE=$PIDNAME.pid                    #pid file
 PIDSPATH=/var/run
- 
-DESCRIPTION="Nginx Sngular version {{ nginx_major_version }}.{{ nginx_minor_version }}"
- 
+
+DESCRIPTION="Nginx s|ngular version {{ nginx_major_version }}.{{ nginx_minor_version }}"
+
 RUNAS=root                              #user to run as
- 
+
 SCRIPT_OK=0                             #ala error codes
 SCRIPT_ERROR=1                          #ala error codes
 TRUE=1                                  #boolean
 FALSE=0                                 #boolean
- 
+
 lockfile=/var/lock/subsys/nginx
 NGINX_CONF_FILE="/etc/nginx/nginx.conf"
- 
+
 #------------------------------------------------------------------------------
 #                               Simple Tests
 #------------------------------------------------------------------------------
- 
+
 #test if nginx is a file and executable
 test -x $DAEMON || exit 0
- 
-# Include nginx defaults if available
-if [ -f /etc/default/nginx ] ; then
-        . /etc/default/nginx
-fi
- 
+
 #set exit condition
 #set -e
- 
+
 #------------------------------------------------------------------------------
 #                               Functions
 #------------------------------------------------------------------------------
- 
+
 setFilePerms(){
- 
+
         if [ -f $PIDSPATH/$PIDFILE ]; then
                 chmod 400 $PIDSPATH/$PIDFILE
         fi
 }
- 
+
 configtest() {
-	$DAEMON -t -c $NGINX_CONF_FILE
+    $DAEMON -t -c $NGINX_CONF_FILE
 }
- 
+
 getPSCount() {
-	return `pgrep -f $PS | wc -l`
+    return `pgrep -f $PS | wc -l`
 }
- 
+
 isRunning() {
         if [ $1 ]; then
                 pidof_daemon $1
                 PID=$?
- 
+
                 if [ $PID -gt 0 ]; then
                         return 1
                 else
@@ -82,7 +75,7 @@ isRunning() {
         else
                 pidof_daemon
                 PID=$?
- 
+
                 if [ $PID -gt 0 ]; then
                         return 1
                 else
@@ -90,13 +83,13 @@ isRunning() {
                 fi
         fi
 }
- 
+
 #courtesy of php-fpm
 wait_for_pid () {
         try=0
- 
+
         while test $try -lt 35 ; do
- 
+
                 case "$1" in
                         'created')
                         if [ -f "$2" ] ; then
@@ -104,7 +97,7 @@ wait_for_pid () {
                                 break
                         fi
                         ;;
- 
+
                         'removed')
                         if [ ! -f "$2" ] ; then
                                 try=''
@@ -112,45 +105,45 @@ wait_for_pid () {
                         fi
                         ;;
                 esac
- 
+
                 #echo -n .
                 try=`expr $try + 1`
                 sleep 1
         done
 }
- 
+
 status(){
-	isRunning
-	isAlive=$?
- 
-	if [ "${isAlive}" -eq $TRUE ]; then
+    isRunning
+    isAlive=$?
+
+    if [ "${isAlive}" -eq $TRUE ]; then
                 echo "$PIDNAME encontrado corriendo en :  `pidof $PS`"
         else
                 echo "$PIDNAME no esta corriendo."
         fi
- 
- 
+
+
 }
- 
+
 removePIDFile(){
-	if [ $1 ]; then
+    if [ $1 ]; then
                 if [ -f $1 ]; then
-        	        rm -f $1
-	        fi
+                    rm -f $1
+            fi
         else
-		#Do default removal
-		if [ -f $PIDSPATH/$PIDFILE ]; then
-        	        rm -f $PIDSPATH/$PIDFILE
-	        fi
+        #Do default removal
+        if [ -f $PIDSPATH/$PIDFILE ]; then
+                    rm -f $PIDSPATH/$PIDFILE
+            fi
         fi
 }
- 
+
 start() {
-        log_daemon_msg "Arrancando $DESCRIPTION"
- 
-	isRunning
-	isAlive=$?
- 
+    log_daemon_msg "Arrancando $DESCRIPTION"
+
+    isRunning
+    isAlive=$?
+
         if [ "${isAlive}" -eq $TRUE ]; then
                 log_end_msg $SCRIPT_ERROR
         else
@@ -160,109 +153,109 @@ start() {
                 log_end_msg $SCRIPT_OK
         fi
 }
- 
+
 stop() {
-	log_daemon_msg "Deteniendo $DESCRIPTION"
- 
-	isRunning
-	isAlive=$?
+    log_daemon_msg "Deteniendo $DESCRIPTION"
+
+    isRunning
+    isAlive=$?
         if [ "${isAlive}" -eq $TRUE ]; then
                 start-stop-daemon --stop --quiet --pidfile $PIDSPATH/$PIDFILE
- 
-		wait_for_pid 'removed' $PIDSPATH/$PIDFILE
- 
+
+        wait_for_pid 'removed' $PIDSPATH/$PIDFILE
+
                 if [ -n "$try" ] ; then
                         log_end_msg $SCRIPT_ERROR
                 else
                         removePIDFile
-	                log_end_msg $SCRIPT_OK
+                    log_end_msg $SCRIPT_OK
                 fi
- 
+
         else
                 log_end_msg $SCRIPT_ERROR
         fi
 }
- 
+
 reload() {
-	configtest || return $?
- 
-	log_daemon_msg "Recargando (via HUP) $DESCRIPTION"
- 
+    configtest || return $?
+
+    log_daemon_msg "Recargando (via HUP) $DESCRIPTION"
+
         isRunning
         if [ $? -eq $TRUE ]; then
-		`killall -HUP $PS` #to be safe
- 
+        `killall -HUP $PS` #to be safe
+
                 log_end_msg $SCRIPT_OK
         else
                 log_end_msg $SCRIPT_ERROR
         fi
 }
- 
+
 quietupgrade() {
-	log_daemon_msg "Actualizando de manera sielenciosa $DESCRIPTION"
- 
+    log_daemon_msg "Actualizando de manera sielenciosa $DESCRIPTION"
+
         isRunning
         isAlive=$?
         if [ "${isAlive}" -eq $TRUE ]; then
-		kill -USR2 `cat $PIDSPATH/$PIDFILE`
-		kill -WINCH `cat $PIDSPATH/$PIDFILE.oldbin`
- 
-		isRunning
-		isAlive=$?
-		if [ "${isAlive}" -eq $TRUE ]; then
-			kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
-			wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
+        kill -USR2 `cat $PIDSPATH/$PIDFILE`
+        kill -WINCH `cat $PIDSPATH/$PIDFILE.oldbin`
+
+        isRunning
+        isAlive=$?
+        if [ "${isAlive}" -eq $TRUE ]; then
+            kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
+            wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
                         removePIDFile $PIDSPATH/$PIDFILE.oldbin
- 
-			log_end_msg $SCRIPT_OK
-		else
-			log_end_msg $SCRIPT_ERROR
- 
-			log_daemon_msg "ERROR! volviendo a $DESCRIPTION"
- 
-			kill -HUP `cat $PIDSPATH/$PIDFILE`
-			kill -TERM `cat $PIDSPATH/$PIDFILE.oldbin`
-			kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
- 
-			wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
+
+            log_end_msg $SCRIPT_OK
+        else
+            log_end_msg $SCRIPT_ERROR
+
+            log_daemon_msg "ERROR! volviendo a $DESCRIPTION"
+
+            kill -HUP `cat $PIDSPATH/$PIDFILE`
+            kill -TERM `cat $PIDSPATH/$PIDFILE.oldbin`
+            kill -QUIT `cat $PIDSPATH/$PIDFILE.oldbin`
+
+            wait_for_pid 'removed' $PIDSPATH/$PIDFILE.oldbin
                         removePIDFile $PIDSPATH/$PIDFILE.oldbin
- 
-			log_end_msg $SCRIPT_ok
-		fi
+
+            log_end_msg $SCRIPT_ok
+        fi
         else
                 log_end_msg $SCRIPT_ERROR
         fi
 }
- 
+
 terminate() {
         log_daemon_msg "Forzando detención (via KILL) $DESCRIPTION"
- 
-	PIDS=`pidof $PS` || true
- 
-	[ -e $PIDSPATH/$PIDFILE ] && PIDS2=`cat $PIDSPATH/$PIDFILE`
- 
-	for i in $PIDS; do
-		if [ "$i" = "$PIDS2" ]; then
-	        	kill $i
+
+    PIDS=`pidof $PS` || true
+
+    [ -e $PIDSPATH/$PIDFILE ] && PIDS2=`cat $PIDSPATH/$PIDFILE`
+
+    for i in $PIDS; do
+        if [ "$i" = "$PIDS2" ]; then
+                kill $i
                         wait_for_pid 'removed' $PIDSPATH/$PIDFILE
-			removePIDFile
-		fi
-	done
- 
-	log_end_msg $SCRIPT_OK
+            removePIDFile
+        fi
+    done
+
+    log_end_msg $SCRIPT_OK
 }
- 
+
 destroy() {
-	log_daemon_msg "Destruyendo (via KILLALL) $DESCRIPTION"
-	killall $PS -q >> /dev/null 2>&1
-	log_end_msg $SCRIPT_OK
+    log_daemon_msg "Destruyendo (via KILLALL) $DESCRIPTION"
+    killall $PS -q >> /dev/null 2>&1
+    log_end_msg $SCRIPT_OK
 }
- 
+
 pidof_daemon() {
     PIDS=`pidof $PS` || true
- 
+
     [ -e $PIDSPATH/$PIDFILE ] && PIDS2=`cat $PIDSPATH/$PIDFILE`
- 
+
     for i in $PIDS; do
         if [ "$i" = "$PIDS2" ]; then
             return 1
@@ -270,43 +263,43 @@ pidof_daemon() {
     done
     return 0
 }
- 
+
 case "$1" in
   start)
-	start
+    start
         ;;
   stop)
-	stop
+    stop
         ;;
   restart|force-reload)
-	stop
-	sleep 1
-	start
+    stop
+    sleep 1
+    start
         ;;
   reload)
-	$1
-	;;
+    $1
+    ;;
   status)
-	status
-	;;
+    status
+    ;;
   configtest)
         $1
         ;;
   quietupgrade)
-	$1
-	;;
+    $1
+    ;;
   terminate)
-	$1
-	;;
+    $1
+    ;;
   destroy)
-	$1
-	;;
+    $1
+    ;;
   *)
-	FULLPATH=/etc/init.d/$PS
-	echo "Uso: $FULLPATH {start|stop|restart|force-reload|status|configtest|quietupgrade|terminate|destroy}"
-	echo "       El comando 'destroy' solo usalo si estas sudando piedras." 
-	exit 1
-	;;
+    FULLPATH=/etc/init.d/$PS
+    echo "Uso: $FULLPATH {start|stop|restart|force-reload|status|configtest|quietupgrade|terminate|destroy}"
+    echo "       El comando 'destroy' solo usalo si estas sudando piedras."
+    exit 1
+    ;;
 esac
- 
+
 exit 0
